In [355]:
import pandas as pd
import numpy as np

# 5.1 Introduction to pandas Data Structures

### Series

In [356]:
obj = pd.Series([4, 7, -5, 3])

In [357]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

And so on...

In [358]:
obj.values

array([ 4,  7, -5,  3])

In [359]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [360]:
obj2 = pd.Series([4,7,-5,3],index = ['d','b','a','c'])

In [361]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [362]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [363]:
obj2['a']

-5

In [364]:
obj2['d'] = 6

In [365]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [366]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [367]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

#### numpy.exp is e**x

In [368]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [369]:
'b' in obj2

True

In [370]:
'e' in obj2

False

In [371]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000,'Utah': 5000}

#### checking mixed data

In [372]:
sdata2 = {'Ohio': 35000, 'Texas': 'a', 'Oregon': 16000,'Utah': 5000}

In [373]:
obj3 = pd.Series(sdata)
obj3_2 = pd.Series(sdata2)


In [374]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [375]:
obj3_2
np.exp(obj3_2)

TypeError: loop of ufunc does not support argument 0 of type int which has no callable exp method

In [376]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [377]:
obj4 = pd.Series(sdata, index=states)

In [378]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [379]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [380]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [381]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [382]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [383]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [384]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [385]:
obj4.name = 'population'

In [386]:
obj4.index.name = 'state'

In [387]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [388]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [389]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [390]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000,2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [391]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [392]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [393]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [394]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
        index = ['one', 'two', 'three', 'four', 'five', 'six'])

In [395]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [396]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [397]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [398]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [399]:
frame3 = frame2.year #checking if data frame is returned

In [400]:
frame3

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [401]:
type(frame3) #it's a series (duh)

pandas.core.series.Series

In [402]:
frame2['debt'] = 16.5

In [403]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [404]:
frame2['debt'] = np.arange(6.)

In [405]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [406]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [407]:
frame2['debt'] = val

In [408]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [409]:
frame2['eastern'] = frame2.state == 'Ohio'

In [410]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [411]:
del frame2['eastern']

In [412]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [413]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
    'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [414]:
frame3 = pd.DataFrame(pop, index=[2000,2001,2002])

In [415]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

#### Appear to be runing into issues with ordered dicts vs the sample
dicts are not entering sorted as described in the book


In [416]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [417]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [418]:
pdata = {'Ohio': frame3['Ohio'][:-1],
    'Nevada': frame3['Nevada'][:2]}

In [419]:
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [420]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

### semicolon to seperate lines, Jupyter feature?

In [421]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [422]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [423]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [424]:
obj = pd.Series(range(3), index=['a','b','c'])

In [425]:
index = obj.index

In [426]:
index

Index(['a', 'b', 'c'], dtype='object')

In [427]:
index[1:]

Index(['b', 'c'], dtype='object')

In [428]:
index[1] = 'd'

TypeError: Index does not support mutable operations

In [429]:
labels = pd.Index(np.arange(3))

In [430]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [431]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [432]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [433]:
obj2.index is labels

True

### faffing about with obj2.index is labels, permanantly lost the connection when labels changed

In [434]:
labels = [5,3,6]

In [435]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [436]:
obj2.index is labels

False

In [437]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [438]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [439]:
obj2.index

Int64Index([0, 1, 2], dtype='int64')

In [440]:
'Ohio' in frame3.columns

True

In [441]:
2003 in frame3.index

False

In [442]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [443]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## 5.2 Essential Functionality

In [444]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [445]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [446]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [447]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

#### ffill, interpelate blanks (forward fill)

In [448]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [449]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [450]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [451]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [452]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
    index=['a','c','d'],columns=['Ohio', 'Texas', 'California'])

In [453]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [454]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [455]:
frame2 = frame.reindex(['a','b','c','d'])

In [456]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [457]:
states = ['Texas', 'Utah', 'California']

In [458]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [459]:
frame.columns is states

False

In [460]:
states

['Texas', 'Utah', 'California']

In [461]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

## loc no loonger works to reindex non existant values

In [462]:
frame.reindex(index=['a','b','c','d'],columns=states)

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

### Dropping Entries from an Axis

In [463]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [464]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [465]:
new_obj = obj.drop('c')

In [466]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [467]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

#### why tuples to reshape

In [468]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
    index=['Ohio', 'Colorado', 'Utah', 'New York'],
    columns=['one', 'two', 'three', 'four'])

In [469]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [470]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [471]:
data.drop('two', axis = 1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [472]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [473]:
obj.drop('c', inplace = True)

In [474]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

### Indexing, Selection, and Filtering

In [475]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [476]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [477]:
obj['b']

1.0

In [478]:
obj[1]

1.0

In [479]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [480]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [481]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [482]:
obj[obj <2]

a    0.0
b    1.0
dtype: float64

In [483]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [484]:
obj['b':'c'] = 5

In [485]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [486]:
data = pd.DataFrame(np.arange(16).reshape((4,4,)), 
    index=['Ohio', 'Colorado', 'Utah', 'New York'], 
    columns=['one', 'two', 'three', 'four'])

In [487]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [488]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [489]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [490]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [491]:
data[data['three'] >5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [492]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [493]:
data[data < 5] = 0

In [494]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### Selection with loc and iloc

In [495]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int64

In [496]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [497]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [498]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [499]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [500]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [501]:
ser = pd.Series(np.arange(3.))


In [502]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [503]:
ser[-1]

KeyError: -1

In [504]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [505]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [506]:
ser2[-1]

2.0

In [507]:
ser[:1]

0    0.0
dtype: float64

In [508]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [509]:
ser.iloc[:1]

0    0.0
dtype: float64

### Arithmetic and Data Alignment

In [510]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [511]:
s2 =pd.Series([-2.1, 3.6, -1.5, 4, 3.1], 
    index=['a', 'c', 'e', 'f', 'g'])

In [512]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [513]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [514]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [515]:
df1 = pd.DataFrame(np.arange(9.).reshape((3,3)), columns=list('bcd'),
    index=['Ohio', 'Texas', 'Colorado'])

In [516]:
df2 = pd.DataFrame(np.arange(12.).reshape((4,3)), columns=list('bde'), 
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [517]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [518]:
df1 = pd.DataFrame({'A': [1,2]})

In [519]:
df2 = pd.DataFrame({'B': [3,4]})

In [520]:
df1

A
0  1
1  2

In [521]:
df2

B
0  3
1  4

In [522]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

### Arithmetic methods with fill values

In [523]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), 
    columns=list('abcd'))

In [524]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),
    columns=list('abcde'))

In [525]:
df2.loc[1,'b'] = np.nan

In [526]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [527]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [528]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [529]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [530]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [531]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [532]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [533]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

### Operations between DataFrame and Series

In [534]:
arr = np.arange(12.).reshape((3,4))

In [535]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [536]:
arr[0]

array([0., 1., 2., 3.])

In [537]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [538]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)), 
    columns=list('bde'), 
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [539]:
series = frame.iloc[0]

In [540]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [541]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [542]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [543]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [544]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [545]:
series3 = frame['d']

In [546]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [547]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [548]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Funtion Application and Mapping

In [549]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'), 
    index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [550]:
frame

b         d         e
Utah    1.528886  1.470642 -0.824962
Ohio   -0.358137  0.331272 -0.343029
Texas  -0.924329  0.723248 -1.059303
Oregon  0.373941  0.926652 -0.889012

In [551]:
np.abs(frame)

b         d         e
Utah    1.528886  1.470642  0.824962
Ohio    0.358137  0.331272  0.343029
Texas   0.924329  0.723248  1.059303
Oregon  0.373941  0.926652  0.889012

In [552]:
f = lambda x: x.max() - x.min()

In [553]:
frame.apply(f)

b    2.453215
d    1.139370
e    0.716274
dtype: float64

In [554]:
frame.apply(f, axis = 'columns')

Utah      2.353848
Ohio      0.689408
Texas     1.782551
Oregon    1.815664
dtype: float64

In [555]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [556]:
frame.apply(f)

b         d         e
min -0.924329  0.331272 -1.059303
max  1.528886  1.470642 -0.343029

In [557]:
format = lambda x: '%.2f' % x

In [558]:
frame.applymap(format)

b     d      e
Utah     1.53  1.47  -0.82
Ohio    -0.36  0.33  -0.34
Texas   -0.92  0.72  -1.06
Oregon   0.37  0.93  -0.89

In [559]:
frame['e'].map(format)

Utah      -0.82
Ohio      -0.34
Texas     -1.06
Oregon    -0.89
Name: e, dtype: object

### Sorting and Ranking

In [560]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [561]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [562]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)), 
    index=['three', 'one'], 
    columns = ['d', 'a', 'b', 'c'])

In [563]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [564]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [565]:
frame.sort_index(axis = 1, ascending = False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [566]:
obj = pd.Series([4,7,-3,2])

In [567]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [568]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [569]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [570]:
frame = pd.DataFrame({'b': [4,7,-3,2], 'a': [0,1,0,1]})

In [571]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [572]:
frame =frame.reindex(['a','b'], axis=1)
# putting in order of book

In [573]:
frame.sort_values(by='b')

a  b
2  0 -3
3  1  2
0  0  4
1  1  7

In [574]:
frame.sort_values(by=['a','b'])

a  b
2  0 -3
0  0  4
3  1  2
1  1  7

In [575]:
obj = pd.Series([7,-5,7,4,2,0,4])

In [576]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [577]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [578]:
obj.rank(method='max')

0    7.0
1    1.0
2    7.0
3    5.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [579]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [580]:
frame = pd.DataFrame({'a': [0, 1, 0, 1], 'b': [4.3, 7, -3, 2], 'c': [-2, 5, 8, -2.5]})

In [581]:
frame

a    b    c
0  0  4.3 -2.0
1  1  7.0  5.0
2  0 -3.0  8.0
3  1  2.0 -2.5

In [582]:
frame.rank(axis='columns')

a    b    c
0  2.0  3.0  1.0
1  1.0  3.0  2.0
2  2.0  1.0  3.0
3  2.0  3.0  1.0

### Axis Indexes with Duplicate Labels

In [583]:
obj = pd.Series(range(5), index=['a','a','b', 'b', 'c'])

In [584]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [585]:
obj.index.is_unique

False

In [586]:
obj['a']

a    0
a    1
dtype: int64

In [587]:
obj['b']

b    2
b    3
dtype: int64

In [588]:
obj['c']

4

In [589]:
df = pd.DataFrame(np.random.randn(4,3), index=['a', 'a', 'b', 'b'])

In [590]:
df.loc['b']

0         1         2
b  0.066620  0.621774 -0.545009
b  0.156223 -1.516609  0.273868

In [591]:
df

0         1         2
a -0.946948 -2.100206  0.276389
a -0.382282 -1.653858  0.256467
b  0.066620  0.621774 -0.545009
b  0.156223 -1.516609  0.273868

## 5.3 Summarizing and Computing Descriptive Statistics

In [592]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5], 
    [np.nan, np.nan], [0.75, -1.3]], index=list('abcd'), columns = ['one', 'two'])

In [593]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [594]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [595]:
df.sum(axis = 'columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

### Nan values are zero if the whole row (change since book written?)

In [596]:
df.mean(axis=1, skipna =False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [597]:
df.idxmax()

one    b
two    d
dtype: object

In [598]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [599]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [600]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [601]:
obj = pd.Series(['a', 'a', 'b', 'c']*4)

In [602]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [607]:
import pandas_datareader.data as web

In [609]:
all_data = {ticker: web.get_data_yahoo(ticker)
    for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [610]:
price = pd.DataFrame({ticker: data['Adj Close']
    for ticker, data in all_data.items()})

In [613]:
volume = pd.DataFrame({ticker: data['Volume']
    for ticker, data in all_data.items()})

In [627]:
returns = price.pct_change()
type(returns)




pandas.core.frame.DataFrame

In [628]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2021-11-04 -0.003499 -0.005671  0.007305  0.012896
2021-11-05  0.003582  0.022838 -0.001129  0.003753
2021-11-08 -0.005553  0.007524  0.002767  0.000740
2021-11-09  0.002459 -0.016680 -0.003086 -0.000690
2021-11-10 -0.019163 -0.005213 -0.015330 -0.017571

In [629]:
returns['MSFT'].corr(returns['IBM'])

0.5054960881148057

In [630]:
returns['MSFT'].cov(returns['IBM'])

0.00014444247802062753

In [631]:
returns.MSFT.corr(returns.IBM)

0.5054960881148057

In [632]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.438958  0.736373  0.660783
IBM   0.438958  1.000000  0.505496  0.474820
MSFT  0.736373  0.505496  1.000000  0.778334
GOOG  0.660783  0.474820  0.778334  1.000000

In [633]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000362  0.000138  0.000241  0.000213
IBM   0.000138  0.000275  0.000144  0.000134
MSFT  0.000241  0.000144  0.000297  0.000227
GOOG  0.000213  0.000134  0.000227  0.000288

In [636]:
returns.corrwith(returns.IBM)

AAPL    0.438958
IBM     1.000000
MSFT    0.505496
GOOG    0.474820
dtype: float64

In [638]:
returns.corrwith(volume)

AAPL   -0.071638
IBM    -0.138348
MSFT   -0.062375
GOOG   -0.114436
dtype: float64

In [641]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [642]:
uniques = obj.unique()

In [643]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [645]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [646]:
pd.value_counts(obj.values, sort=False)

b    2
c    3
d    1
a    3
dtype: int64

In [647]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [648]:
mask = obj.isin(['b','c'])

In [649]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [650]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [651]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [652]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [654]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [655]:
data = pd.DataFrame({'Qu1': [1,3,4,3,4],
    'Qu2': [2,3,1,2,3], 
    'Qu3': [1,5,2,4,4]})

In [656]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [668]:
result = data.apply(pd.value_counts).fillna(0)

In [669]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0